name: Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            source venv/bin/activate
            python -m unittest  
